
version: '3.8'

services:
  # FastAPI application service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - VECTOR_DB_HOST=vectordb
      - VECTOR_DB_PORT=8080
      - DEBUG=true
    volumes:
      - .:/app
    depends_on:
      - vectordb
    networks:
      - vectorhub-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Weaviate vector database service
  vectordb:
    image: semitechnologies/weaviate:1.19.0
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - vectorhub-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 30s
      timeout: 10s
      retries: 3

# Named volumes for persistent data
volumes:
  weaviate_data:
    driver: local

# Custom network for service communication
networks:
  vectorhub-network:
    driver: bridge
